---
 - name: install ntpd
   apt: pkg=ntp state=installed
   tags:
    - packages
    - ntp

 - name: configure ntp
   template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=root group=root mode=640
   notify:
    - restart ntp
   tags:
    - config
    - ntp


 - name: ensure ntp is enabled
   service: name=ntp enabled=yes