---
- name: install ferm
  apt: pkg=ferm state=installed

- name: create dirs
  file: path="/etc/ferm/{{ item }}" state=directory mode=750 owner=root group=root
  with_items:
  - input
  - input6
  - forward
  - forward6
  - output
  - output6

- name: ferm.conf
  template: src=ferm.conf dest=/etc/ferm/ferm.conf
  notify:
    - restart ferm