---
 - name: setup /etc/network/interfaces
   template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root

 - name: config /etc/resolv.conf
   template: src=resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root
   when: "'network_dns_servers' is defined"

# Todo:
# ra
# forwarding
# ipv6 disable/enable