---
 - name: install packages
   apt: pkg={{ item }} state=installed
   with_items:
    - git
    - etckeeper
   tags:
    - etckeeper
    - packages

 - name: configure etckeeper to use git
   lineinfile: dest=/etc/etckeeper/etckeeper.conf
    regexp="^VCS=.*"
    line="VCS=\"git\""
   tags:
    - etckeeper

 - name: init repository
   shell: etckeeper init
   args:
    creates: /etc/.git
   tags:
    - etckeeper